version: '3.6'
services:
  backendsvc:
    image: nullstring/gooutdoorsy:latest
    restart: always
    environment:
      - "DATABASE_URL=postgresql://root:root@postgres:5432/testingwithrentals?sslmode=disable&connect_timeout=30"
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: mdillon/postgis:11
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root # Use pwd file instead
      - POSTGRES_DB=testingwithrentals
      # To work with the healthcheck - avoids "UTC [312] FATAL:  database "root" does not exist"
      - PGPASSWORD=root
      - PGUSER=root
      - PGDATABASE=testingwithrentals
    expose:
      - "5432"
    volumes:
      - ./sql-init.sql:/docker-entrypoint-initdb.d/sql-init.sql
    healthcheck:
      test: [ "CMD", "/usr/bin/pg_isready", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s